apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: aiops-system
  labels:
    app.kubernetes.io/name: mongodb
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: aiops-system
  labels:
    app.kubernetes.io/name: mongodb
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
