apiVersion: v1
kind: PersistentVolume
metadata:
  name: aiops-backend-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: "/mnt/data/aiops-backend"
    type: DirectoryOrCreate
